### ISSUE TITLE
@ signification ?

### ISSUE THREAD

**Issue by nsankar** [nums-project/nums#561]
What does @ signify. 

I mean how to interpret print((x.T @ x).get()) or print((x.T @ x).shape) ?
Is it correct in my understanding that x.get() operation will be processed first and then x.T ?

**Comment by briancpark** [comment]
`@` is just matrix multiply operator used in [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) and NumS.

To answer your second question, the `.get()` operator is a blocking call that synchronizes output and serves it to the user. Any operations preceding it will be executed until it finishes computing the result that `.get()` is being called on. When we actually want numerical results in the end, we call `.get()` on a `BlockArray` variable, such as `x.get()`.

So `(x.T @ x).get()` will first do a matrix multiply (or inner/outer product depending on dimensions of `x`). Then the call to `.get()` will wait for matrix multiply to finish and output the results to the user in a NumPy array. Simply, `.get()` just converts a NumS data structure to a NumPy ndarray. Ideally, calling `.get()` is what you want to do at the end of a series of operations.

Let us know if that was unclear or if you have any other questions!

**Comment by nsankar** [comment]
Got it @briancpark . Thank you.
