### ISSUE TITLE
IP address detection / head node selection failure

### ISSUE THREAD

**Issue by pspillai** [nums-project/nums#58]
Nums currently detects local IP address by trying to connect to an external address (8.8.8.8).  This causes issues on private clusters, and can get the wrong IP address when there are multiple interfaces (e.g. with public facing IP address, and private IP address within the cluster).  

On a cluster with public IP addresses and private IP addresses (used for the ray cluster), the public one is detected, and thus no "head" node is assigned (since no ray node has this public ip address), and nums fails to initialize.

A possible fix is to get all local interface ip addresses, and check if any match the ray node IPs.  Alternatively, if none match, just pick any node as the "head".

**Comment by elibol** [comment]
Thanks for the issue. This is addressed by #59.

Knowing which node is head vs. a worker is not actually required, but if you want to exclude the head node for use, you can specify `nums.core.settings.use_head = False`. To do this, nums needs to know which node is the head node.

If nums is unable to detect the Ray head ip, then the head node is treated as a worker node. #59 fixes a bug that prevented this from happening. I've also added a way to explicitly specify the head node ip using `nums.core.settings.head_ip`, which is only needed if detection of head node is failing and `use_head = False`. If `use_head = False` and head node detection fails, a warning is logged indicating that the head node will be used by nums.

This fix is also released under version `0.2.1`.
